censura/urls.py
from django.urls import path
from censura import views

app_name = 'censura'

urlpatterns = [
    path('', views.index, name='index'),

    path('login/', views.user_login, name='login'),
    
    path('logout/', views.user_logout, name='logout'),

    path('signup/', views.signup, name='signup'),
    
    path('about/', views.about, name='about'),
    
    path('user/<str:username>/edit-profile/', views.edit_profile, name='edit_profile'),
    
    path('user/<str:username>/create-review/', views.create_review, name='create_review_account'),

    path('user/<str:username>/', views.my_account, name='my_account'),

    path('user/<str:username>/my-favourites/', views.my_favourites, name='my_favourites'),
    
    path('user/<str:username>/least-favourites/', views.least_favourites, name='least_favourites'),

    path('user/<str:username>/my-reviews/', views.my_reviews, name='my_reviews'),

    path('reviews/<int:review_id>/toggle-like/', views.toggle_review_like, name='toggle_review_like'),
    
    path('user/<str:username>/add-friend/', views.add_friend, name='add_friend'),
    
    path('user/<str:username>/remove-friend/', views.remove_friend, name='remove_friend'),
    
    path('user/<str:username>/friends/', views.friends, name='friends'),

    path('movies/', views.view_movies, name='movies'),

    path('movies/<slug:movie_name_slug>/toggle-favourite/', views.toggle_favourite, name='toggle_favourite'),
    
    path('movies/<slug:movie_name_slug>', views.view_movie, name='movie'),
    
    path('movies/<slug:movie_name_slug>/review/<str:username>', views.review, name='review'),
    
    path('movies/<slug:movie_name_slug>/create-review', views.create_review, name='create_review'),
    
    path('find-friends/', views.find_friends, name='find_friends'),
    
    path('comment/<int:comment_id>/delete', views.delete_comment, name='delete_comment'),
    
    path('reviews/<int:review_id>/delete', views.delete_review, name='delete_review'),

    path('ajax/search-movies/', views.ajax_search_movies, name='ajax_search_movies'),
    
    path('movies/<slug:movie_name_slug>/sorted-reviews/', views.ajax_sorted_reviews, name='ajax_sorted_reviews'),

]

censura_project/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include
from censura import views

urlpatterns = [
    path('', views.index, name='index'),
    path('censura/', include('censura.urls')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

censura/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import UserProfile, Movie, Review, Comment

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta:
        model = User
        fields = ('username', 'email', 'password')
        
        labels = {
            'username': 'Your Username',
            'email': 'Email Address',
            'password': 'Create Password',
        }
        
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.label_suffix = ''
        for myField in self.fields:
            self.fields[myField].widget.attrs['class'] = 'form-control'


class UserProfileForm(forms.ModelForm):
    
    class Meta:
        model = UserProfile
        fields = ('picture',)
    


class ReviewForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        self.movie_instance = kwargs.pop('movie_instance', None)
        super().__init__(*args, **kwargs)
        if self.movie_instance:
            self.fields['movie'].initial = self.movie_instance
            self.fields['movie'].widget = forms.HiddenInput()

    class Meta:
        model = Review
        fields = ['movie', 'rating', 'text']
        widgets = {
            'rating': forms.NumberInput(attrs={
                'min': 0, 
                'max': 10, 
                'class': 'form-control rating-selector'
            }),
            'text': forms.Textarea(attrs={'rows': 3}),
        }
            
class CommentForm(forms.ModelForm):
    text = forms.TextInput()
    class Meta:
        model = Comment
        fields = ('text',)
        
        widgets = {
            'text': forms.Textarea(attrs={
                'class': 'form-control',
                'placeholder': 'Add a comment...',
                'rows': 3
            }),
        }
        labels = {
            'text': 'Leave a comment',
        }
        

censura/views.py
from django.http import JsonResponse, HttpResponse, HttpResponseForbidden
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from django.urls import reverse
from .forms import UserForm, UserProfileForm, ReviewForm, CommentForm
from .models import UserProfile, Review, Movie, Comment, Genre
from django.http import JsonResponse


def index(request):

    context_dict = {}

    movies_release_order = Movie.objects.order_by('-release_date')
    five_most_revent = movies_release_order[:5]

    movies_by_popularity = Movie.objects.order_by('-popularity')
    five_most_popular = movies_by_popularity[:5]

    context_dict['movies_release_order'] = five_most_revent
    context_dict['movies_by_popularity'] = five_most_popular

    return render(request, 'censura/index.html', context=context_dict)


def user_login(request):
    error_message = None

    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(username=username, password=password)

        if user:
            if user.is_active:
                login(request, user)
                return redirect(reverse('censura:my_account', args=[request.user.username]))
        else:
            error_message = "Invalid Login Details"

    return render(request, 'censura/login.html', {'error_message': error_message})


def user_logout(request):
    logout(request)
    return redirect(reverse('censura:index'))


def my_account(request, username):
    user_profile = get_object_or_404(UserProfile, user__username=username)
    user_reviews = Review.objects.filter(
        user=user_profile.user).order_by('-created_at')[:3]
    liked_movies = user_profile.likes.all()
    favourites = liked_movies[:5]

    least_favourites = Review.objects.filter(
        user=user_profile.user, rating__lt=5).order_by('rating')[:5]
    least_favourites = [review.movie for review in least_favourites]

    context = {
        'user_profile': user_profile,
        'user_reviews': user_reviews,
        'liked_movies': liked_movies,
        'favourites': favourites,
        'least_favourites': least_favourites, 
    }
    return render(request, 'censura/account.html', context)


@login_required
def friends(request, username):
    user_profile = get_object_or_404(UserProfile, user__username=username)
    friends = user_profile.friends.all()
    context = {
        'friends': friends,
        'num_friends': len(friends),
        'username': username,
    }
    return render(request, 'censura/friends.html', context=context)


@login_required
def my_favourites(request, username):
    if request.method == 'POST':
        return redirect(reverse('censura:movies'))
    
    user_profile = get_object_or_404(UserProfile, user__username=username)
    all_genres = Genre.objects.all()

    query = request.GET.get('q', '')
    genre = request.GET.get('genre', '')
    year = request.GET.get('year', '')

    liked_movies = user_profile.likes.all().order_by('-release_date')

    if query:
        liked_movies = liked_movies.filter(name__icontains=query)

    if genre:
        liked_movies = liked_movies.filter(genre__name=genre)

    if year:
        liked_movies = liked_movies.filter(release_date__icontains=year)

    all_genres = Genre.objects.all()
    paginator = Paginator(liked_movies, 24)
    page = request.GET.get('page')
    movies = paginator.get_page(page)
    context_dict = {"movies": movies, "favourites": True, "genres": all_genres}
    return render(request, 'censura/movies.html', context=context_dict)


def least_favourites(request, username):
    user_profile = get_object_or_404(UserProfile, user__username=username)
    least_favourites = Review.objects.filter(
        user=user_profile.user).order_by('rating')[:5]
    least_favourites = [review.movie for review in least_favourites]

    context = {
        'movies': least_favourites,
        'username': username,
    }
    return render(request, 'censura/movies.html', context=context)


@login_required
def toggle_favourite(request, movie_name_slug):
    movie = get_object_or_404(Movie, slug=movie_name_slug)
    user_profile, created = UserProfile.objects.get_or_create(
        user=request.user)

    if movie in user_profile.likes.all():
        user_profile.likes.remove(movie)
        is_favourite = False
    else:
        user_profile.likes.add(movie)
        is_favourite = True

    return JsonResponse({'success': True, 'is_favourite': is_favourite})

@login_required
def toggle_review_like(request, review_id):
    review = get_object_or_404(Review, id=review_id)
    
    if request.user in review.likes.all():
        review.likes.remove(request.user)
        liked = False
    else:
        review.likes.add(request.user)
        liked = True
        
    return JsonResponse({
        'success': True, 
        'liked': liked,
        'total_likes': review.likes.count()
    })


def my_reviews(request, username):
    user = UserProfile.objects.get(user__username=username).user
    user_reviews = Review.objects.filter(user=user).order_by('-created_at')
    paginator = Paginator(user_reviews, 5)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)

    if request.headers.get('X-Requested-With') == 'XMLHttpRequest':
        return JsonResponse({
            'items': [
                {
                    'type': 'review',
                    'movie': review.movie.name,
                    'rating': review.rating,
                    'text': review.text,
                    'likes_count': review.likes.count(),
                    'created_at': review.created_at.strftime("%B %d, %Y"),
                    'url': reverse('censura:review', args=[review.movie.slug, review.user.username])
                } for review in page_obj
            ],
            'has_next': page_obj.has_next(),
        })

    return render(request, 'censura/read_review.html', {'reviews': page_obj, 'review_user': user})


def signup(request):
    if request.method == 'POST':
        user_form = UserForm(request.POST)

        if user_form.is_valid():
            user = user_form.save(commit=False)
            user.set_password(user.password)  # hash password
            user.save()

            # Login the user
            login(request, user)
            return redirect(reverse('censura:edit_profile', args=[user.username]))
    else:
        user_form = UserForm()

    return render(request, 'censura/signup.html', {'user_form': user_form})


@login_required
def add_friend(request, username):
    if request.method == 'POST':
        user_to_add = get_object_or_404(User, username=username)
        user_profile = request.user.userprofile
        friend_profile = user_to_add.userprofile

        if friend_profile not in user_profile.friends.all():
            user_profile.friends.add(friend_profile)

        next_url = request.POST.get('next', reverse('censura:my_account', args=[username]))
        return redirect(next_url)

    return JsonResponse({'success': False, 'message': 'Invalid request'})


@login_required
def remove_friend(request, username):
    if request.method == 'POST':
        user_to_remove = get_object_or_404(User, username=username)
        user_profile = request.user.userprofile
        friend_profile = user_to_remove.userprofile

        if friend_profile in user_profile.friends.all():
            user_profile.friends.remove(friend_profile)

        return redirect(reverse("censura:my_account", args=[username]))

    return JsonResponse({'success': False, 'message': 'Invalid request'})


@login_required
def edit_profile(request, username):
    user = request.user
    if user.username != username:  # prevent others from editing
        return HttpResponseForbidden("You are not allowed to edit this profile.")

    if request.method == 'POST':
        profile_form = UserProfileForm(
            request.POST, request.FILES, instance=user.userprofile)

        if profile_form.is_valid():
            profile_form.save()
            return redirect(reverse('censura:my_account', args=[user.username]))
    else:
        profile_form = UserProfileForm(instance=user.userprofile)

    return render(request, 'censura/edit-profile.html', {'profile_form': profile_form})


@login_required
def find_friends(request):
    current_user_profile = request.user.userprofile
    users = UserProfile.objects.filter(user__username__isnull=False).exclude(user__username='').exclude(user=current_user_profile.user)
    friends = current_user_profile.friends.all()
    context = {'users': users, 'friends': friends}
    return render(request, 'censura/find_friends.html', context=context)


def about(request):
    return render(request, 'censura/about.html')


def view_movies(request):
    if request.method == 'POST':
        return redirect(reverse('censura:movies'))
    
    query = request.GET.get('q', '')
    genre = request.GET.get('genre', '')
    year = request.GET.get('year', '')

    movies = Movie.objects.all()

    if query:
        movies = movies.filter(name__icontains=query)

    if genre:
        movies = movies.filter(genre__name=genre)

    if year:
        movies = movies.filter(release_date__icontains=year)
    
    all_genres = Genre.objects.all()
    paginator = Paginator(movies, 24)
    page = request.GET.get('page')
    movies = paginator.get_page(page)
    context_dict = {"movies": movies, "genres": all_genres}
    return render(request, 'censura/movies.html', context=context_dict)


def view_movie(request, movie_name_slug):
    context_dict = {}

    try:
        movie = Movie.objects.get(slug=movie_name_slug)
        movie.genre.prefetch_related("genre").all()
        context_dict['movie'] = movie

templates/censura/account.html
{% extends 'censura/base.html' %}

{% block title_block %}
	{{ user_profile.user.username }}'s account
{% endblock %}

{% block body_block %}


    <div class="account-header">
        <!-- Account Title -->
        <div class="account-title-container">
            <h2 class="account-title">{{ user_profile.user.username }}'s Account</h2>
        </div>


        <div class="profile-picture-container">
            <img class="profile-picture" src="{{ user_profile.picture.url }}" alt="Profile Picture">
        </div>

    
        <div class="account-buttons">
            {% if user != user_profile.user %}
                {% if user_profile in user.userprofile.friends.all %}
                    <form method="POST" action="{% url 'censura:remove_friend' user_profile.user.username %}">
                        {% csrf_token %}
                        <button type="submit" class="btn btn-danger">Remove Friend</button>
                    </form>
                {% else %}
                    <form method="POST" action="{% url 'censura:add_friend' user_profile.user.username %}">
                        {% csrf_token %}
                        <button type="submit" class="btn btn-primary">Add Friend</button>
                    </form>
                {% endif %}
            {% endif %}
            <a href="{% url 'censura:friends' user_profile.user %}" class="btn btn-secondary">Friends</a>
            {% if user == user_profile.user %}
                <a href="{% url 'censura:my_reviews' user_profile.user.username %}" class="btn btn-secondary">My Reviews</a>
                <a href="{% url 'censura:my_favourites' user_profile.user.username %}" class="btn btn-secondary">My Favourites</a>
                <a href="{% url 'censura:edit_profile' user_profile.user.username %}" class="btn btn-secondary">Edit Profile</a>
            {% else %}
                <a href="{% url 'censura:my_reviews' user_profile.user.username %}" class="btn btn-secondary">See {{ user_profile.user.username }}'s Reviews</a>
                <a href="{% url 'censura:my_favourites' user_profile.user.username %}" class="btn btn-secondary">See {{ user_profile.user.username }}'s Favourites</a>
            {% endif %}
        </div>
    </div>



    <div class="account-page-container">
        <!-- Left Section -->
        <div class="account-left">
            <div>
                <h2>
                    {{ user_profile.user.username }}'s <a href="{% url 'censura:my_favourites' user_profile.user.username %}">favourites</a>
                </h2>
                <ul class="small-movie-list">
                    {% for movie in favourites %}
                        <li class="small-movie-element">
                            <a style="text-decoration: none;" class="movie" href="{% url 'censura:movie' movie.slug %}">
                                <img src="{{ movie.image.url }}" alt="{{ movie.name }}">
                                <span>{{ movie.name }}</span>
                            </a>
                        </li>
                    {% endfor %}
                </ul>
            </div>

            <div>
                <h2>
                    {{ user_profile.user.username }}'s <a href="{% url 'censura:least_favourites' user_profile.user.username %}">least favourites</a>
                </h2>
                <ul class="small-movie-list">
                    {% for movie in least_favourites %}
                        <li class="small-movie-element">
                            <a style="text-decoration: none;" class="movie" href="{% url 'censura:movie' movie.slug %}">
                                <img src="{{ movie.image.url }}" alt="{{ movie.name }}">
                                <span>{{ movie.name }}</span>
                            </a>
                        </li>
                    {% endfor %}
                </ul>
            </div>
        </div>

        <!-- Right Section -->
        <div class="account-right">
            <h2>{{ user_profile.user.username }}'s Recent Reviews</h2>
            <ul class="movie-reviews">
                {% for review in user_reviews %}
                    <li class="review">
                        <h4>Reviewed: <a href="{% url 'censura:movie' review.movie.slug %}">{{ review.movie.name }}</a></h4>
                        <p>Rating: {{ review.rating }}/10</p>
                        <p>{{ review.text|truncatewords:20 }}</p> <!-- Truncate long reviews -->
                        <p class="review-date">{{ review.created_at|date:"F d, Y" }}</p>
                        <a href="{% url 'censura:review' review.movie.slug review.user.username %}">See Thread</a>
                    </li>
                {% endfor %}
            </ul>
        </div>
    </div>
    
{% endblock %}

templates/censura/base.html
<!-- filepath: c:\Computing\Computing\Year_2\WAD2\Team_Project_3C\WAD2-3C-Censura\templates\censura\base.html -->
<!DOCTYPE html>
{% load staticfiles %}

<html lang="en">
    <head>
        <meta charset="UTF-8">
        <title>
            Censura -
            {% block title_block %}
                Welcome to Censura!
            {% endblock %}
        </title>
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.4.1/dist/css/bootstrap.min.css"
            integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <link rel="stylesheet" href="{% static 'css/styles.css' %}">
        <meta name="csrf-token" content="{{ csrf_token }}">
        <script src="{% static 'js/review_likes.js' %}"></script>
        <script src="{% static 'js/heart_button.js' %}"></script>
    </head>

    <div>
        <ul class="navbar">
            <li class="brand"><a href="{% url 'censura:index' %}">Censura</a></li>

            <div class="nav-links">

                {% if user.is_authenticated %}
                    <li><a href="{% url 'censura:my_account' user.username %}">
                        My Account</a></li>

                    <li><a href="{% url 'censura:edit_profile' user.username %}">
                        Edit Profile</a></li>
                        
                    <li><a href="{% url 'censura:find_friends' %}">Find Friends</a></li>
                    <li><a href="{% url 'censura:logout' %}">Log out</a></li>
                {% else %}
                    <li><a href="{% url 'censura:login' %}">Login</a></li>
                    <li><a href="{% url 'censura:signup' %}">Sign Up</a></li>

                {% endif %}
                
                <li><a href="{% url 'censura:movies' %}">Movies</a></li>
                <li><a href="{% url 'censura:about' %}">About</a></li>
                <li><a href="{% url 'censura:index' %}">Home</a></li>

            </div>

        </ul>
    </div>

    <body data-is-authenticated="{% if user.is_authenticated %}true{% else %}false{% endif %}">
    <div style="padding: 2%">
        {% block body_block %}
        
        {% endblock %}
    </div>
    

    <script>
        var searchMoviesUrl = "{% url 'censura:ajax_search_movies' %}";  // Pass Django URL to JS
    </script>
    <script src="{% static 'js/review_sort.js' %}"></script>
    
    </body>

</html>

templates/censura/find_friends.html
{% extends 'censura/base.html'%}

{% block title_block %}
    Find Friends
{% endblock %}

{% block body_block %}
<div class="find-friends-wrapper">
    <div class="find-friends-container">
        <h2>Find Friends</h2>
        <ul class="find-friends-list">
            {% for user in users %}
                {% if user.user.username %}
                    <li>
                        <a href="{% url 'censura:my_account' user.user.username %}">{{ user.user.username }}</a>
                        {% if user in friends %}
                            <span class="friend-status">(Friend)</span>
                        {% else %}
                            <form method="POST" action="{% url 'censura:add_friend' user.user.username %}">
                                {% csrf_token %}
                                <input type="hidden" name="next" value="{{ request.get_full_path }}">
                                <button type="submit">Add Friend</button>
                            </form>
                        {% endif %}
                    </li>
                {% endif %}
            {% endfor %}
        </ul>
    </div>
</div>
{% endblock %}

templates/censura/index.html
{% extends 'censura/base.html' %}

{% block body_block %}

    <div class="welcome_container">
        {% if user.is_authenticated %}
        <h2>Welcome, {{ user.username }}!</h2>
        {% else %}
        <div class="welcome">
            <h2>New Users</h2>
            <a class="btn btn-dark" role="button" href="{% url 'censura:signup' %}">Sign up</a> for a new account.
        </div>
        
        
        <div class="welcome">
            <h2>Existing Users</h2>
            <a class="btn btn-dark" role="button" href="{% url 'censura:login' %}">Login</a> to your account.
        </div>
        {% endif %}
		
	</div>

    <div style="display: flex; flex-direction: column; align-items: center; text-align: center;">
        <div>
            <h2>Recent Releases</h2>
            <ul class="movie_list">

                {% for movie in movies_release_order %}
                <li class="movie_element">
                    <a style="text-decoration: none;" class="movie" href="{% url 'censura:movie' movie.slug %}">
                        <img src="{{ movie.image.url }}" alt="{{ movie.name }}">
                        <span>{{ movie.name }}</span>
                    </a>
                </li>
                {% endfor %}
            </ul>
        </div>

        <div>
            <h2>Popular Movies</h2>
            <ul class="movie_list">

                {% for movie in movies_by_popularity %}
                <li class="movie_element">
                    <a style="text-decoration: none;" class="movie" href="{% url 'censura:movie' movie.slug %}">
                        <img src="{{ movie.image.url }}" alt="{{ movie.name }}">
                        <span>{{ movie.name }}</span>
                    </a>
                </li>
                {% endfor %}
            </ul>
        </div>
    </div>
    

{% endblock %}

templates/censura/movie.html
{% extends 'censura/base.html' %}

{% block title_block %}
	{% if movie %}
        {{ movie.name }}
    {% endif %}
{% endblock %}

{% block body_block %}
    {% if movie %}
        <h1 class="text-center"><strong>{{ movie.name }}</strong></h1>
        <div style="display: flex; align-items: center; justify-content: center;margin-bottom:100px;">
            <div style="width: 40%; display:flex;align-items:center;justify-content: center">
                <img style="width: 50%;" src="{{ movie.image.url }}" alt="{{ movie.name }}">
                {% if user.is_authenticated %}
                <button class="btn btn-dark favourite-btn" data-movie-slug="{{ movie.slug }}">
                    <span class="heart {% if movie in user.userprofile.likes.all %}filled{% else %}empty{% endif %}">
                        {% if movie in user.userprofile.likes.all %}
                        ❤️
                        {% else %}
                        ♡
                        {% endif %}
                    </span>
                </button>
                {% endif %}
            
                <dl class="row">
                    <dt class="col-sm-3 mb-1">Release Date</dt>
                    <dd class="col-sm-9 mb-1 ml-2">{{ movie.release_date }}</dd>
            
                    <dt class="col-sm-3 mb-1">Director</dt>
                    <dd class="col-sm-9 mb-1 ml-2">{{ movie.director }}</dd>
            
                    <dt class="col-sm-3 mb-1">Genres</dt>
                    <dd class="col-sm-9 mb-1 ml-2">
                        {% for genre in movie.genre.all %}
                        <p class="mb-1">{{ genre.name }}</p>
                        {% endfor %}
                    </dd>
                </dl>
            </div>
            {% else %}
            This movie is not in the database.
            {% endif %}
            <div class="movie-description">
                <p>{{ movie.description }}</p>
            </div>

        </div>
        
    <hr>
    
    <!-- Review section -->
    <div id="user-review" class="review-section">
        <h3 class="text-center">Your Reviews</h3>

        <div class="movie-reviews">

     

            {% if user.is_authenticated %}
                <!-- Display existing user reviews -->
                {% if user_has_reviewed %}
                    {% for review in user_reviews %}
                    <a href="{% if movie.slug %}{% url 'censura:create_review' movie.slug %}{% else %}#{% endif %}" class="btn btn-dark">Edit Review</a>
                    <div class="review">
                        <h4> Reviewed by {{ review.user.username }}</h4>
                        <p>Rating: {{ review.rating }}/10</p>
                        <p>{{ review.text }}</p>
                        <p class="review-date">{{ review.created_at|date:"F d, Y" }}</p>
                    </div>
                    {% endfor %}
                {% else %}
                    <p class="text-center">Have you watched this film and want to share your thoughts?</p>
                    <a href="{% if movie.slug %}{% url 'censura:create_review' movie.slug %}{% else %}# No URL available{% endif %}" class="btn btn-dark">Write a Review</a>
                {% endif %}

            {% else %}
                    <p class="text-center"><a href="{% url 'censura:login' %}">Login</a> to write a review.</p>
            {% endif %}

        </div>
    </div>

    <hr>
    
    <h3 class="text-center">All Reviews</h3>
    {% if all_reviews %}
        <label for="sort" class="text-center d-block">Sort by:</label>
        <select id="sort" class="sort-dropdown mx-auto d-block">
            <option value="created_at" selected>Newest</option>
            <option value="likes">Most Liked</option>
            <option value="rating">Highest Rated</option>
        </select>
        <div id="all-reviews-container" class="review-section" data-movie-slug="{{ movie.slug }}">
            <!-- Display top reviews -->
        
        <div id="all-reviews" class="movie-reviews">
            {% for review in all_reviews %}
            <div class="review" data-review-url="{% url 'censura:review' movie.slug review.user.username %}">
                <h4>Reviewed by <a href="{% url 'censura:my_account' review.user.username %}">{{ review.user.username }}</a></h4>
                <p>Rating: {{ review.rating }}/10</p>
                <p>{{ review.text }}</p>
                {% if user.is_authenticated %}
                <button class="like-review-btn" data-review-id="{{ review.id }}">
                    <span class="thumb {% if user in review.likes.all %}liked{% endif %}">
                        👍 <span class="like-count">{{ review.likes.count }}</span>
                    </span>
                </button>
                {% endif %}
                <a href="{% url 'censura:review' movie.slug review.user.username %}">Read More</a>
                <p class="review-date">{{ review.created_at|date:"F d, Y" }}</p>
            </div>
            {% endfor %}
        </div>       
    {% else %}
        <p class="text-center">No reviews yet. Be the first to review!</p>
    {% endif %}
         </div>
{% endblock %}

templates/censura/read_review.html
{% extends 'censura/base.html' %}
{% load static %} 
{% block title_block %}
    {{ review_user.username }}'s Reviews
{% endblock %}

{% block body_block %}

<h2>{{ review_user.username }}'s Reviews</h2>

<div id="infinite-scroll-container" class="movie-reviews">
    {% for review in reviews %}
    <div class="review scroll-item">
        <div style="display: flex; justify-content: space-between;">
            <h4>
                <a href="{% url 'censura:movie' review.movie.slug %}">{{ review.movie.name }}</a>
            </h4>
            {% if user.is_authenticated %}
            <button class="like-review-btn" data-review-id="{{ review.id }}">
                <span class="thumb {% if user in review.likes.all %}liked{% endif %}">
                    👍 <span class="like-count">{{ review.likes.count }}</span>
                </span>
            </button>
            {% endif %}
        </div>
        <p>Rating: {{ review.rating }}/10</p>
        <p>{{ review.text }}</p>
        <a href="{% url 'censura:review' review.movie.slug review.user.username %}">See Thread</a>
        {% if review.user == user %}
            <a class="btn btn-dark" href="{% url 'censura:delete_review' review.id %}"><i class="fa fa-trash"></i></a>
        {% endif %}
        <p class="review-date">{{ review.created_at|date:"F d, Y" }}</p>
    </div>
    {% endfor %}
</div>

<div style="margin-top: 20px;">
    <a class="btn btn-dark" href="{% url 'censura:my_account' user.username %}">Back</a>
</div>

<div id="loading" style="display: none;">Loading more...</div>

{% endblock %}

templates/censura/reviews.html
{% extends 'censura/base.html' %}

{% block body_block %}
	Hello!
{% endblock %}